// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aomimdggwfqenvfivihm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFvbWltZGdnd2ZxZW52Zml2aWhtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkyMDQyODEsImV4cCI6MjA1NDc4MDI4MX0.6b_9LcMDVv5T8i_2aDt0Ccpfqhnphss0xlT7EpvICRk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);